name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run smoke tests
        run: pytest -m smoke --alluredir=allure-results-smoke
      - name: Upload Allure results (smoke)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: allure-results-smoke

  sanity:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sanity tests
        run: pytest -m sanity --alluredir=allure-results-sanity
      - name: Upload Allure results (sanity)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-sanity
          path: allure-results-sanity

  regression:
    runs-on: ubuntu-latest
    needs: sanity
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run regression tests
        run: pytest -m regression --alluredir=allure-results-regression
      - name: Upload Allure results (regression)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression
          path: allure-results-regression

  report:
    runs-on: ubuntu-latest
    needs: [smoke, sanity, regression]
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-smoke
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-sanity
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: allure-results-regression
        continue-on-error: true
      - name: Install Allure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      - name: Merge Allure results
        run: |
          mkdir merged-allure-results
          cp -r allure-results-smoke/* merged-allure-results/ || true
          cp -r allure-results-sanity/* merged-allure-results/ || true
          cp -r allure-results-regression/* merged-allure-results/ || true
      - name: Generate Allure report
        run: |
          allure generate merged-allure-results --clean -o allure-report
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report